### ISSUE TITLE
Call to undefined function has_custom_logo() in header.php

### ISSUE THREAD

**Issue by ddorstijn** [holger1411/understrap#191]
When I try to view the site it gives only generates a part of the error to then give the following error:

> Fatal error: Uncaught Error: Call to undefined function has_custom_logo() in /usr/share/wordpress/wp-content/themes/understrap/header.php:50 Stack trace: #0 /usr/share/wordpress/wp-includes/template.php(562): require_once() #1 /usr/share/wordpress/wp-includes/template.php(521): load_template('/usr/share/word...', true) #2 /usr/share/wordpress/wp-includes/general-template.php(45): locate_template(Array, true) #3 /usr/share/wordpress/wp-content/themes/understrap/home.php(13): get_header() #4 /usr/share/wordpress/wp-includes/template-loader.php(89): include('/usr/share/word...') #5 /usr/share/wordpress/wp-blog-header.php(16): require_once('/usr/share/word...') #6 /usr/share/wordpress/index.php(17): require('/usr/share/word...') #7 {main} thrown in /usr/share/wordpress/wp-content/themes/understrap/header.php on line 50

When I comment out this lines it works fine. So it doesn't seem like there is something wrong with the configuration. But maybe I missed something. Didn't see it addressed before either.

**Comment by ddorstijn** [comment]
After some extended amount of research I found out it was a Wordpress installation problem which caused the version to stay at 4.2. Fixed it by manually updating it. Will close this issue as it has nothing to do with the theme.
