### ISSUE TITLE
Gulp watch not working

### ISSUE THREAD

**Issue by jdfweb** [holger1411/understrap#414]
I've built many sites with this theme so far, it's great!

I usually develop on a PC, but I have a Mac now. Just installed homebrew, npm and gulp.

Ran gulp watch, and got this error:

[22:26:37] Using gulpfile /Applications/MAMP/htdocs/cma/wp-content/themes/cma/gulpfile.js
[22:26:37] Starting 'watch'...
[22:26:37] Finished 'watch' after 14 ms
[22:26:40] Starting 'styles'...
[22:26:40] Starting 'sass'...
[22:26:41] Finished 'sass' after 438 ms
[22:26:41] Starting 'minify-css'...
[22:26:41] Finished 'minify-css' after 390 ms
[22:26:41] Finished 'styles' after 831 ms
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 1.22 ms
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 963 μs
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 503 μs
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 376 μs
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 315 μs
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 353 μs
[22:26:41] Starting 'imagemin'...
[22:26:41] Finished 'imagemin' after 438 μs

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Applications/MAMP/htdocs/cma/wp-content/themes/cma/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Any idea what the fix is?!

**Comment by washaweb** [comment]
This is still the same issue with the imagemin task that run in an infinite loop. I've had the same problem. 
To avoid this, a temporary fix would be to remove 'imagemin' task from the watch task in the gulpfile.js. 
Doing this, you'll have to run the imagemin separately with a ´$ gulp imagemin´ command, each time you add a new media.

**Comment by jdfweb** [comment]
@washaweb Awesome! Fixed it. Thank you.
